using AdobeKoreanShortcuts;
var failures = new List<string>();
void Check(string name, bool actual) { if (!actual) failures.Add(name); Console.WriteLine($"{(actual ? "PASS" : "FAIL")} {name}"); }
var safe = new FocusFacts(true, false, false, false, true);
Check("Korean workspace letter enabled", Policy.ShouldBridge(safe, 0x56, false, false, false));
Check("text editor protected", !Policy.ShouldBridge(safe with { Text = true }, 0x56, false, false, false));
Check("native caret protected", !Policy.ShouldBridge(safe with { Caret = true }, 0x56, false, false, false));
Check("dialog protected", !Policy.ShouldBridge(safe with { Dialog = true }, 0x56, false, false, false));
Check("unknown or stale focus protected", !Policy.ShouldBridge(safe with { Fresh = false }, 0x56, false, false, false));
Check("unrecognized focus untouched", !Policy.ShouldBridge(safe with { Eligible = false }, 0x56, false, false, false));
Check("Ctrl shortcut untouched", !Policy.ShouldBridge(safe, 0x56, true, false, false));
Check("Alt shortcut untouched", !Policy.ShouldBridge(safe, 0x56, false, true, false));
Check("Windows shortcut untouched", !Policy.ShouldBridge(safe, 0x56, false, false, true));
Check("Hangul toggle untouched", !Policy.ShouldBridge(safe, 0x15, false, false, false));
Check("space untouched", !Policy.ShouldBridge(safe, 0x20, false, false, false));
Check("bracket shortcut enabled", Policy.ShouldBridge(safe, 0xDB, false, false, false));
Check("number untouched", !Policy.ShouldBridge(safe, 0x31, false, false, false));
Check("fresh same-context sample accepted",Policy.Fresh(100,200,true,true,true));
Check("slow UIA sample rejected",!Policy.Fresh(100,500,true,true,true));
Check("different window rejected",!Policy.Fresh(100,200,false,true,true));
Check("different native focus rejected",!Policy.Fresh(100,200,true,false,true));
Check("key down scan preserved",KeyMessage.Pack(0x2f,false,false,false)==0x002f0001);
Check("repeat flag preserved",KeyMessage.Pack(0x2f,false,false,true)==0x402f0001);
Check("key up flags preserved",KeyMessage.Pack(0x2f,false,true,true)==unchecked((nint)(int)0xc02f0001));
Check("extended key flag preserved",KeyMessage.Pack(0x2f,true,false,false)==0x012f0001);
Check("unknown Adobe context protected", !Policy.KnownWorkspace("AfterFX","ControlType.Pane/"));
Check("AE composition recognized", Policy.KnownWorkspace("AfterFX","ControlType.Pane/AE Composition/"));
Check("AE timeline recognized", Policy.KnownWorkspace("AfterFX","ControlType.Pane/AE Timeline/"));
Check("Premiere timeline recognized", Policy.KnownWorkspace("Adobe Premiere Pro","ControlType.Pane/Timeline/"));
Check("Premiere program monitor recognized", Policy.KnownWorkspace("Adobe Premiere Pro","ControlType.Pane/Program Monitor/"));
Check("unverified apps protected", !Policy.KnownWorkspace("Photoshop","ControlType.Pane/"));
var presses=new PressTracker();
Check("first physical down eligible",presses.Down(0x56));
Check("passthrough repeat cannot start bridge",!presses.Down(0x56));
presses.Up(0x56);
Check("new physical press eligible after release",presses.Down(0x56));
Check("pause or focus transition keeps press ownership",!presses.Down(0x56));
Check("generic button workspace",Policy.GenericWorkspace("Button",true,false,false,false,null));
Check("generic read-only browser document",Policy.GenericWorkspace("Document",true,false,false,true,true));
Check("generic editable document protected",!Policy.GenericWorkspace("Document",true,false,false,true,false));
Check("generic unknown text mutability protected",!Policy.GenericWorkspace("Document",true,false,false,true,null));
Check("generic password protected",!Policy.GenericWorkspace("Button",true,true,false,false,null));
Check("generic writable value protected",!Policy.GenericWorkspace("Button",true,false,true,false,null));
Check("generic edit protected",!Policy.GenericWorkspace("Edit",true,false,false,true,true));
Check("generic combo protected",!Policy.GenericWorkspace("ComboBox",true,false,false,false,null));
Check("generic custom canvas unknown protected",!Policy.GenericWorkspace("Custom",true,false,false,false,null));
Check("generic nonfocusable container protected",!Policy.GenericWorkspace("Button",false,false,false,false,null));
Check("tree type-to-search preserved",!Policy.GenericWorkspace("TreeItem",true,false,false,false,null));
Check("sample before transition rejected",!Policy.AfterTransition(100,120));
Check("sample during transition rejected",!Policy.AfterTransition(150,120));
Check("sample after transition accepted",Policy.AfterTransition(220,120));
Check("Premiere source monitor recognized",Policy.KnownWorkspace("Adobe Premiere Pro","ControlType.Pane/Source Monitor/"));
if(failures.Count>0)throw new Exception(string.Join(", ",failures));
Console.WriteLine("All policy/key-message checks passed.");
